USE dbVendas;

DECLARE @NUM_NOTAS INTEGER;
DECLARE @ARQUIVO_BKP VARCHAR(100);
DECLARE @DATA DATE

SET @DATA = '2022-03-03';
SET @ARQUIVO_BKP = 'L:\Backups\politica_backup_20220303.bak';

DELETE FROM tb_controle_backups;

-- 1 DA MANHÃ - FULL (DATABASE WITH INT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (1,'BACKUP FULL 1 AM', @NUM_NOTAS);
BACKUP DATABASE dbVendas TO DISK = @ARQUIVO_BKP WITH INIT;

-- 4 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (2,'BACKUP INCREMENTAL 4 AM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 6 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (3,'BACKUP INCREMENTAL 6 AM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 8 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (4,'BACKUP INCREMENTAL 8 AM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 9 DA MANHÃ - FULL (DATABASE WITH DIFFERENTIAL)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (5,'BACKUP DIFFERENTIAL 9 AM', @NUM_NOTAS);
BACKUP DATABASE dbVendas TO DISK = @ARQUIVO_BKP WITH DIFFERENTIAL;

-- 10 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (6,'BACKUP INCREMENTAL 10 AM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 12 DA MANHÃ - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (7,'BACKUP INCREMENTAL 12 AM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 2 DA TARDE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (8,'BACKUP INCREMENTAL 2 PM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 2 DA TARDE - FULL (DATABASE WITH DIFERENCIAL)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (9,'BACKUP DIFFERENTIAL 2 PM', @NUM_NOTAS);
BACKUP DATABASE dbVendas TO DISK = @ARQUIVO_BKP WITH DIFFERENTIAL;

-- 3 DA TARDE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (10,'BACKUP INCREMENTAL 3 PM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 5 DA TARDE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (11,'BACKUP INCREMENTAL 5 PM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 7 DA NOITE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (12,'BACKUP INCREMENTAL 7 PM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

-- 9 DA NOITE - INCREMENTAL (LOG WITH NOINT)

EXEC IncluiNotasDia @DATA;
SELECT @NUM_NOTAS = COUNT(*) FROM tb_nota;
INSERT INTO tb_controle_backups VALUES (13,'BACKUP INCREMENTAL 9 PM', @NUM_NOTAS);
BACKUP LOG dbVendas TO DISK = @ARQUIVO_BKP WITH NOINIT;

SELECT * FROM tb_controle_backups;

USE MASTER;
ALTER DATABASE dbVendas SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
DROP DATABASE dbVendas;
